### ISSUE TITLE
AR functionality not working

### ISSUE THREAD

**Issue by santhamethran** [Snapchat/camera-kit-unity-sample#4]
After following the instructions provided in the readme file, I built the application for Android. When I ran it on my mobile device, the button functionality worked, but the camera did not open; instead, I could only see my home screen. I checked the camera permission option in the app info, and it's enabled. How can I resolve this issue?

![Screenshot_2024-02-28-17-24-55-44_b87267ec644ddf170b0d5169d21e18c3](https://github.com/Snapchat/camera-kit-unity-sample/assets/66728258/ef0ccc23-2188-4a2e-8ac4-cb67223321e3)

**Comment by ohthreeness** [comment]
I had the same. This error showed every time I tried to open one of the lenses:

2024-05-15 14:47:52.439 19771-19855 Unity                   com.fictionalcompany.mygame          E  AndroidJavaException: java.lang.ClassNotFoundException: com.snap.camerakitsamples.unity.android.MainUnityActivity
                                                                                                    java.lang.ClassNotFoundException: com.snap.camerakitsamples.unity.android.MainUnityActivity
                                                                                                    	at java.lang.Class.classForName(Native Method)
                                                                                                    	at java.lang.Class.forName(Class.java:536)
                                                                                                    	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
                                                                                                    	at com.unity3d.player.UnityPlayer.-$$Nest$mnativeRender(Unknown Source:0)
                                                                                                    	at com.unity3d.player.UnityPlayer$F$a.handleMessage(Unknown Source:122)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at com.unity3d.player.UnityPlayer$F.run(Unknown Source:24)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.snap.camerakitsamples.unity.android.MainUnityActivity" on path: DexPathList[[zip file "/data/app/~~-MsCRQm6HvIN3xg3kGaJpQ==/com.fictionalcompany.mygame-g0hQrGoakmSDU7r_6LPyZg==/base.apk"],nativeLibraryDirectories=[/data/app/~~-MsCRQm6HvI

**Comment by Alvarden15** [comment]
> I had the same. This error showed every time I tried to open one of the lenses:
> 
> 2024-05-15 14:47:52.439 19771-19855 Unity com.fictionalcompany.mygame E AndroidJavaException: java.lang.ClassNotFoundException: com.snap.camerakitsamples.unity.android.MainUnityActivity java.lang.ClassNotFoundException: com.snap.camerakitsamples.unity.android.MainUnityActivity at java.lang.Class.classForName(Native Method) at java.lang.Class.forName(Class.java:536) at com.unity3d.player.UnityPlayer.nativeRender(Native Method) at com.unity3d.player.UnityPlayer.-$$Nest$mnativeRender(Unknown Source:0) at com.unity3d.player.UnityPlayer$F$a.handleMessage(Unknown Source:122) at android.os.Handler.dispatchMessage(Handler.java:103) at android.os.Looper.loopOnce(Looper.java:232) at android.os.Looper.loop(Looper.java:317) at com.unity3d.player.UnityPlayer$F.run(Unknown Source:24) Caused by: java.lang.ClassNotFoundException: Didn't find class "com.snap.camerakitsamples.unity.android.MainUnityActivity" on path: DexPathList[[zip file "/data/app/~-MsCRQm6HvIN3xg3kGaJpQ==/com.fictionalcompany.mygame-g0hQrGoakmSDU7r_6LPyZg==/base.apk"],nativeLibraryDirectories=[/data/app/~-MsCRQm6HvI

Hello there.
I'm also having the same issue here.

**Comment by Alvarden15** [comment]
> After following the instructions provided in the readme file, I built the application for Android. When I ran it on my mobile device, the button functionality worked, but the camera did not open; instead, I could only see my home screen. I checked the camera permission option in the app info, and it's enabled. How can I resolve this issue?
> 
> ![Screenshot_2024-02-28-17-24-55-44_b87267ec644ddf170b0d5169d21e18c3](https://private-user-images.githubusercontent.com/66728258/308539470-ef0ccc23-2188-4a2e-8ac4-cb67223321e3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMDY1NjIsIm5iZiI6MTczMDMwNjI2MiwicGF0aCI6Ii82NjcyODI1OC8zMDg1Mzk0NzAtZWYwY2NjMjMtMjE4OC00YTJlLThhYzQtY2I2NzIyMzMyMWUzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDE2Mzc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyYzdhNjgxZTdjNmI1MTU5NTc3YTFhZGExZWIzMThlNDA5NjZjMWIwZDE3NTdkZTRhZGJlMzU1ZGU4OTczNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Xqn-zSU4QLNdnYimv_LJOzPmwulWka51-O8vb25ovy0)

Hey there. I'm trying the same sample too and i'm having the same problem, the logcat shows me this.
![l597neb51d](https://github.com/user-attachments/assets/d9354a65-d74c-47ee-a982-bb6e0783d5d1)

**Comment by likeaguest** [comment]
Same here. Is there a way to resolve this?

**Comment by Alvarden15** [comment]
> Same here. Is there a way to resolve this?

Yeah, i think they abandoned this project at this point.
